import Head from "next/head"
import { Footer } from "../Footer"
import { Header } from "../Header"
import { DefaultLayoutProps } from "./defaultLayout.model"
import styles from "./defaultLayout.module.scss"

export const DefaultLayoutComponent = ({ children }: DefaultLayoutProps) => (
  <>
    <Head>
      <title>Poke-Adsmurai</title>
      <meta
        name="description"
        content="Generated by create next app and Created by Maxi Pezzotta"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main className={styles.container}>{children}</main>
    <Footer />
  </>
)
